In [1]:
from numpy import *
import random as rd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
def update_params(params, gradients, learning_rate):
    return params - learning_rate * gradients

In [3]:
def get_gradient(X, y, params):
    h = y - np.dot(X, params)
    gradients = np.zeros(len(params))
    for i in range(len(gradients)):
        gradients[i] = - 1* np.dot(h, X[:, i]) / float(len(y))
    return gradients

In [4]:
def compute_loss(X, y, params):
    return np.sum((y - np.dot(X, params)) ** 2) / (2 * float(len(X)))

In [5]:
def gradient_descent(X, y, learning_rate, num_iterations):
    num_params = X.shape[1]
    #params = np.random.rand(1, num_params)
    #params = np.squeeze(params) # convert 2D matrix to 1D array 
    params = np.array([0, 0])
    #while True:
    for i in range(num_iterations):
        old_loss = compute_loss(X, y, params)
        print("Iteration %d | Cost: %f" % (i, old_loss))
        gradients = get_gradient(X, y, params)
        print("Gradient", gradients)
        params = update_params(params, gradients, learning_rate)
        new_loss = compute_loss(X, y, params)
        if abs(new_loss - old_loss) < 0.00001:
            break
        #print('old_loss: ' + str(old_loss) + ', new_loss: ' + str(new_loss))

    return params

In [6]:
points = genfromtxt('data.csv', delimiter = ',')
points = np.insert(points, 0, 1, axis = 1)
X = points[:,:-1]
y = points[:, -1]
#print(X)
#print(y)

params = gradient_descent(X, y, learning_rate = 0.0001, num_iterations = 2)
print("params", params)

Iteration 0 | Cost: 2782.553917
Gradient [  -72.73505055 -3685.3514868 ]
Iteration 1 | Cost: 1593.133459
Gradient [  -54.6849074  -2766.98863588]
params [ 0.012742    0.64523401]


In [7]:
"""
points = genfromtxt('CCPP.csv', delimiter = ',', skip_header = 1)
points = points[:, [1, 4]]
points = np.insert(points, 0, 1, axis = 1)
X = points[:,:-1]
y = points[:, -1]
print(X)
print(y)
params = gradient_descent(X, y, learning_rate = 0.001, num_iterations = 10000)
params = gradient_descent(X, y, learning_rate = 0.0004, num_iterations = 100000)
print(params)
"""

"\npoints = genfromtxt('CCPP.csv', delimiter = ',', skip_header = 1)\npoints = points[:, [1, 4]]\npoints = np.insert(points, 0, 1, axis = 1)\nX = points[:,:-1]\ny = points[:, -1]\nprint(X)\nprint(y)\nparams = gradient_descent(X, y, learning_rate = 0.001, num_iterations = 10000)\nparams = gradient_descent(X, y, learning_rate = 0.0004, num_iterations = 100000)\nprint(params)\n"

In [8]:
#plt.scatter(X[:, 1], y, color='black')
#x = np.r_[0 : 80 : 11]
#plt.plot(x, -0.99*x + 508.83216289, label = 'manual', color = 'green')
#plt.show()

In [9]:
X = np.arange(0, 12).reshape(4, 3)
print(X)
print(len(X))

y = np.arange(1, 5)
print(y)
params = np.arange(3, 6)
print(params)

for k in range(2):
    old_loss = compute_loss(X, y, params)
    print('old_loss: ' + str(old_loss))
    gradients = get_gradient(X, y, params)
    print('gradients: ' + str(gradients))
    params = update_params(params, gradients, 0.0001)
    print('new_params: ' + str(params))
    new_loss = compute_loss(X, y, params)
    print('new_loss: ' + str(new_loss))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
4
[1 2 3 4]
[3 4 5]
old_loss: 2910.75
gradients: [ 426.   491.5  557. ]
new_params: [ 2.9574   3.95085  4.9443 ]
new_loss: 2837.88212075
old_loss: 2837.88212075
gradients: [ 420.63285   485.308775  549.9847  ]
new_params: [ 2.91533671  3.90231912  4.88930153]
new_loss: 2766.83842741
